name: edunity
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.1.0
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  go_router: ^16.2.4
  iconly: ^1.0.1
  icons_plus: ^5.0.0
  lottie: ^3.3.1
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Black.ttf
        - asset: assets/fonts/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish-ExtraBold.ttf
        - asset: assets/fonts/Mulish-ExtraLight.ttf
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
